from .client import MangaClient, MangaCard, MangaChapter
from .manhuako import ManhuaKoClient
from .tmo import TMOClient
from .mangadex import MangaDexClient
from .mangasin import MangasInClient
from .mcreader import MgekoClient
from .mangakakalot import MangaKakalotClient
from .manganelo import ManganeloClient
from .manganato import ManganatoClient
from .kissmanga import KissMangaClient
from .mangatigre import MangatigreClient
from .mangahasu import MangaHasuClient
from .mangabuddy import MangaBuddyClient
from .asurascans import AsuraScansClient
from .ninemanga import NineMangaClient
from .likemanga import LikeMangaClient
from .mangasee import MangaSeeClient
from .mangadistrict import MangaDistrictClient
from .manga18fx import Manga18fxClient
from .mangapark import MangaParkClient 
from .flamecomics import FlameComicsClient
